In [1]:
import pandas as pd

In [2]:

df_employee = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Ravi", "Anjali"],
    "Department": ["IT", "HR", "IT", "Finance", "Sales", "Sales"],
    "Salary": [65000, 55000, 72000, 60000, 48000, 75000],
    "Experience": [3, 2, 5, 4, 1, 6]
}

In [3]:
df = pd.DataFrame(df_employee)

In [4]:
df

   Emp_ID    Name Department  Salary  Experience
0     101   Rahul         IT   65000           3
1     102   Priya         HR   55000           2
2     103    Amit         IT   72000           5
3     104    Neha    Finance   60000           4
4     105    Ravi      Sales   48000           1
5     106  Anjali      Sales   75000           6

In [5]:
# Question 1: Find employees whose salary is greater than ₹60,000

salary = df[df['Salary'] > 60000]
salary

   Emp_ID    Name Department  Salary  Experience
0     101   Rahul         IT   65000           3
2     103    Amit         IT   72000           5
5     106  Anjali      Sales   75000           6

In [13]:
# Question 2: Create a new column Annual_Salary.

df['annual_salary'] = df['Salary'] * 12

In [14]:
df

   Emp_ID    Name Department  Salary  Experience  annual_salart  annual_salary
0     101   Rahul         IT   65000           3         780000         780000
1     102   Priya         HR   55000           2         660000         660000
2     103    Amit         IT   72000           5         864000         864000
3     104    Neha    Finance   60000           4         720000         720000
4     105    Ravi      Sales   48000           1         576000         576000
5     106  Anjali      Sales   75000           6         900000         900000

In [20]:
df

   Emp_ID    Name Department  Salary  Experience  annual_salary
0     101   Rahul         IT   65000           3         780000
1     102   Priya         HR   55000           2         660000
2     103    Amit         IT   72000           5         864000
3     104    Neha    Finance   60000           4         720000
4     105    Ravi      Sales   48000           1         576000
5     106  Anjali      Sales   75000           6         900000

In [21]:
# Question 3: Find the employee with the highest salary.

highest_salarys = df.loc[df['Salary'].idxmax()]

In [22]:
highest_salarys

Emp_ID              106
Name             Anjali
Department        Sales
Salary            75000
Experience            6
annual_salary    900000
Name: 5, dtype: object

In [23]:
df_sales = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard",
                "Monitor", "Mouse", "Laptop", "Monitor"],
    "Region": ["North", "South", "North", "East",
               "West", "South", "East", "West"],
    "Sales": [80000, 2000, 75000, 3500, 25000, 2500, 85000, 27000],
    "Quantity": [2, 5, 2, 4, 3, 6, 2, 3]
})

print(df_sales)

   Order_ID   Product Region  Sales  Quantity
0      1001    Laptop  North  80000         2
1      1002     Mouse  South   2000         5
2      1003    Laptop  North  75000         2
3      1004  Keyboard   East   3500         4
4      1005   Monitor   West  25000         3
5      1006     Mouse  South   2500         6
6      1007    Laptop   East  85000         2
7      1008   Monitor   West  27000         3

In [26]:
# Filter by product "Laptop" and region "North"

laptop_north = df_sales[(df_sales['Product'] == 'Laptop') & (df_sales['Region'] == 'North')]
laptop_north

   Order_ID Product Region  Sales  Quantity
0      1001  Laptop  North  80000         2
2      1003  Laptop  North  75000         2