In [ ]:
    import pandas as pd
    import numpy as np

In [7]:
# Sample Interview Dataset: Employee Performance Data
data = {
    "Emp_ID":[101,102,103,104,105,106,107,108,109,110],
    "Name": ["Anna", "Ben", "Charlie", "Diana", "Evan", "Fiona", "George", "Hannah", "Ian", "Jack"],
    "Department": ["Sales", "HR", "Sales", "IT", "Sales", "HR", "IT", "Sales", "IT", "Sales"],
    "Salary": [55000, 60000, 72000, 85000, 50000, np.nan, 90000, 68000, 82000, 72000],
    "Sales_Target_Achieved": [True, False, True, True, False, False, True, True, False, True],
    "Region": ["North", "South", "North", "West", "East", "South", "West", "North", "East", "North"]
}

In [10]:
df = pd.DataFrame(data)

In [11]:
df

   Emp_ID     Name Department   Salary  Sales_Target_Achieved Region
0     101     Anna      Sales  55000.0                   True  North
1     102      Ben         HR  60000.0                  False  South
2     103  Charlie      Sales  72000.0                   True  North
3     104    Diana         IT  85000.0                   True   West
4     105     Evan      Sales  50000.0                  False   East
5     106    Fiona         HR      NaN                  False  South
6     107   George         IT  90000.0                   True   West
7     108   Hannah      Sales  68000.0                   True  North
8     109      Ian         IT  82000.0                  False   East
9     110     Jack      Sales  72000.0                   True  North

In [12]:
# Multiple condition filtering (Note the parentheses around each condition)

# Filter by department and sales more than 50k

df_sales = df[(df['Department'] == "Sales") & (df["Salary"] > 50000)]

In [13]:
df_sales

   Emp_ID     Name Department   Salary  Sales_Target_Achieved Region
0     101     Anna      Sales  55000.0                   True  North
2     103  Charlie      Sales  72000.0                   True  North
7     108   Hannah      Sales  68000.0                   True  North
9     110     Jack      Sales  72000.0                   True  North

In [15]:
# Name starting by H

df_names = df[df['Name'].str.startswith('H')]

In [16]:
df_names

   Emp_ID    Name Department   Salary  Sales_Target_Achieved Region
7     108  Hannah      Sales  68000.0                   True  North

In [21]:
# Group BY multiple condion

df_groupby = df.groupby(['Department', 'Region']).agg({'Salary':['mean','max']})

In [22]:
df_groupby

                    Salary
                      mean      max
Department Region
HR         South   60000.0  60000.0
IT         East    82000.0  82000.0
           West    87500.0  90000.0
Sales      East    50000.0  50000.0
           North   66750.0  72000.0

In [27]:
# Group by by single condition
df_groupby2 = df.groupby(['Department']).sum().head(2)

In [28]:
df_groupby2

,Emp_ID,Name,Salary,Sales_Target_Achieved,Region
Department,,,,,
HR,208,BenFiona,60000.0,0,SouthSouth
IT,320,DianaGeorgeIan,257000.0,2,WestWestEast

In [30]:
# Group by with some multiple and single conditions.

df_groupby3 = df.groupby(['Department', 'Region']).agg({'Salary':['mean', 'max', 'min','sum']})

In [31]:
df_groupby3

                    Salary
                      mean      max      min       sum
Department Region
HR         South   60000.0  60000.0  60000.0   60000.0
IT         East    82000.0  82000.0  82000.0   82000.0
           West    87500.0  90000.0  85000.0  175000.0
Sales      East    50000.0  50000.0  50000.0   50000.0
           North   66750.0  72000.0  55000.0  267000.0

In [35]:
# Filter by IT or HR department sales higher than 85000

df_filtered = df[(df['Department'] == 'IT') | (df['Department'] == 'HR') & (df['Salary'] >85000)]

In [36]:
df_filtered

   Emp_ID    Name Department   Salary  Sales_Target_Achieved Region
3     104   Diana         IT  85000.0                   True   West
6     107  George         IT  90000.0                   True   West
8     109     Ian         IT  82000.0                  False   East