In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    'EmployeeID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice Smith', 'Bob Jones', 'Carla Diaz', 'David Lee', 'Eva Kim',
             'Frank Wu', 'Grace Patel', 'Henry Ford', 'Ivy Chen', 'Jack Ryan'],
    'Department': ['Sales', 'Sales', 'Marketing', 'IT', 'Marketing',
                   'IT', 'Sales', 'HR', 'Marketing', 'IT'],
    'Region': ['East', 'West', 'East', 'West', 'East',
               'South', 'South', 'East', 'West', 'South'],
    'Sales': [45000, 54000, np.nan, 30000, 62000,
              28000, 71000, np.nan, 39000, 48000],
    'Rating': [4.5, 3.8, 4.1, np.nan, 4.9, 3.2, 4.7, 3.9, 4.0, 4.4]}

In [4]:
data

{'EmployeeID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
 'Name': ['Alice Smith',
  'Bob Jones',
  'Carla Diaz',
  'David Lee',
  'Eva Kim',
  'Frank Wu',
  'Grace Patel',
  'Henry Ford',
  'Ivy Chen',
  'Jack Ryan'],
 'Department': ['Sales',
  'Sales',
  'Marketing',
  'IT',
  'Marketing',
  'IT',
  'Sales',
  'HR',
  'Marketing',
  'IT'],
 'Region': ['East',
  'West',
  'East',
  'West',
  'East',
  'South',
  'South',
  'East',
  'West',
  'South'],
 'Sales': [45000, 54000, nan, 30000, 62000, 28000, 71000, nan, 39000, 48000],
 'Rating': [4.5, 3.8, 4.1, nan, 4.9, 3.2, 4.7, 3.9, 4.0, 4.4]}

In [5]:
df = pd.DataFrame(data)

In [6]:
df

   EmployeeID         Name Department Region    Sales  Rating
0         101  Alice Smith      Sales   East  45000.0     4.5
1         102    Bob Jones      Sales   West  54000.0     3.8
2         103   Carla Diaz  Marketing   East      NaN     4.1
3         104    David Lee         IT   West  30000.0     NaN
4         105      Eva Kim  Marketing   East  62000.0     4.9
5         106     Frank Wu         IT  South  28000.0     3.2
6         107  Grace Patel      Sales  South  71000.0     4.7
7         108   Henry Ford         HR   East      NaN     3.9
8         109     Ivy Chen  Marketing   West  39000.0     4.0
9         110    Jack Ryan         IT  South  48000.0     4.4

In [7]:
df.info()  # It give column name type and non null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  10 non-null     int64
 1   Name        10 non-null     object
 2   Department  10 non-null     object
 3   Region      10 non-null     object
 4   Sales       8 non-null      float64
 5   Rating      9 non-null      float64
dtypes: float64(2), int64(1), object(3)
memory usage: 608.0+ bytes

In [8]:
df.describe()

       EmployeeID         Sales    Rating
count    10.00000      8.000000  9.000000
mean    105.50000  47125.000000  4.166667
std       3.02765  14970.804922  0.519615
min     101.00000  28000.000000  3.200000
25%     103.25000  36750.000000  3.900000
50%     105.50000  46500.000000  4.100000
75%     107.75000  56000.000000  4.500000
max     110.00000  71000.000000  4.900000

In [9]:
df.shape

(10, 6)

In [10]:
print("\nshapes", df.shape) # here you can also write in this ways.

shapes (10, 6)

In [11]:
df.dtypes

EmployeeID      int64
Name           object
Department     object
Region         object
Sales         float64
Rating        float64
dtype: object

In [12]:
df.isnull().sum()

EmployeeID    0
Name          0
Department    0
Region        0
Sales         2
Rating        1
dtype: int64

In [13]:
# Find sales which grater than 54000

high_sales = df[df['Sales'] > 54000]
high_sales

   EmployeeID         Name Department Region    Sales  Rating
4         105      Eva Kim  Marketing   East  62000.0     4.9
6         107  Grace Patel      Sales  South  71000.0     4.7

In [14]:
# Filer with Ratings which higher than 4.1 and sales > 45000

high_rating  =  df[(df['Rating']> 4.1) & (df['Sales'] > 45000)]
print(high_rating)

   EmployeeID         Name Department Region    Sales  Rating
4         105      Eva Kim  Marketing   East  62000.0     4.9
6         107  Grace Patel      Sales  South  71000.0     4.7
9         110    Jack Ryan         IT  South  48000.0     4.4

In [15]:
# Find sales department with amount greater than 54000

sales_dept = df[(df['Department'] == 'Sales') & (df['Sales'] >54000)]
print(sales_dept)
print(sales_dept[['Name', 'Department', 'Sales']])

   EmployeeID         Name Department Region    Sales  Rating
6         107  Grace Patel      Sales  South  71000.0     4.7
          Name Department    Sales
6  Grace Patel      Sales  71000.0

In [16]:
# How  would you clean nulls here?

sales_null = df[df['Sales'].isnull()]
print(sales_null)

   EmployeeID        Name Department Region  Sales  Rating
2         103  Carla Diaz  Marketing   East    NaN     4.1
7         108  Henry Ford         HR   East    NaN     3.9

In [18]:
# Filter  by Region and sales

region_filter = df[(df['Region'] == 'East') & (df['Sales'] > 54000)]

region_filter

   EmployeeID     Name Department Region    Sales  Rating
4         105  Eva Kim  Marketing   East  62000.0     4.9